import uuid

from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("description", models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(10000)])),
                ("prompt", models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(30000)])),
                ("criteria", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("active", "Active"), ("trashed", "Trashed")], default="active", max_length=16)),
                ("prompt_revision", models.PositiveIntegerField(default=0)),
                ("latest_change_sequence", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("creator", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_projects", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-updated_at",)},
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("owner", "Owner"), ("editor", "Editor"), ("viewer", "Viewer")], default="viewer", max_length=16)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="projects.project")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_memberships", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("project", "role", "joined_at")},
        ),
        migrations.CreateModel(
            name="ProjectInvitation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("invited_email", models.EmailField(max_length=254)),
                ("role", models.CharField(choices=[("editor", "Editor"), ("viewer", "Viewer")], default="viewer", max_length=16)),
                ("token_digest", models.CharField(editable=False, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("inviter", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sent_invitations", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invitations", to="projects.project")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="PromptRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("revision", models.PositiveIntegerField()),
                ("prompt", models.TextField(validators=[django.core.validators.MaxLengthValidator(30000)])),
                ("criteria", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("editor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="prompt_revisions", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="prompt_revisions", to="projects.project")),
            ],
            options={"ordering": ("-project", "-revision")},
        ),
        migrations.CreateModel(
            name="SearchRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("agent_label", models.CharField(blank=True, max_length=160)),
                ("prompt_revision", models.PositiveIntegerField(default=0)),
                ("prompt_snapshot", models.TextField(validators=[django.core.validators.MaxLengthValidator(30000)])),
                ("criteria_snapshot", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("claimed", "Claimed"), ("running", "Running"), ("completed", "Completed"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="queued", max_length=16)),
                ("lease_owner", models.CharField(blank=True, max_length=160)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("claim_token", models.CharField(blank=True, editable=False, max_length=64)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("input_cursor", models.CharField(blank=True, max_length=500)),
                ("output_cursor", models.CharField(blank=True, max_length=500)),
                ("continuation", models.JSONField(blank=True, default=dict)),
                ("result_counts", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(10000)])),
                ("idempotency_key", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agent_token", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="search_runs", to="accounts.agenttoken")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="search_runs", to="projects.project")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="search_runs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source", models.CharField(max_length=160)),
                ("source_listing_id", models.CharField(blank=True, max_length=200)),
                ("canonical_url", models.URLField(max_length=2000)),
                ("source_url", models.URLField(blank=True, max_length=2000)),
                ("identity_hash", models.CharField(blank=True, editable=False, max_length=64)),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(30000)])),
                ("location", models.CharField(blank=True, max_length=500)),
                ("price_display", models.CharField(blank=True, max_length=120)),
                ("price_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ("price_currency", models.CharField(default="USD", max_length=3)),
                ("availability", models.CharField(blank=True, max_length=500)),
                ("housing_type", models.CharField(choices=[("entire", "Entire place"), ("shared", "Shared"), ("unknown", "Unknown")], default="unknown", max_length=16)),
                ("date_confidence", models.CharField(choices=[("strong", "Strong"), ("verify", "Verify"), ("unknown", "Unknown")], default="unknown", max_length=16)),
                ("park_notes", models.CharField(blank=True, max_length=1000)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("verification_notes", models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(10000)])),
                ("status", models.CharField(choices=[("active", "Active"), ("trashed", "Trashed")], default="active", max_length=16)),
                ("trash_reason", models.CharField(blank=True, max_length=1000)),
                ("trashed_at", models.DateTimeField(blank=True, null=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("creator", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_leads", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leads", to="projects.project")),
                ("trashed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="trashed_leads", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-updated_at",)},
        ),
        migrations.CreateModel(
            name="LeadInterest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("lead", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="interests", to="projects.lead")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lead_interests", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="LeadComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lead_comments", to=settings.AUTH_USER_MODEL)),
                ("lead", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="projects.lead")),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="replies", to="projects.leadcomment")),
            ],
            options={"ordering": ("created_at",)},
        ),
        migrations.CreateModel(
            name="ProjectChange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveBigIntegerField()),
                ("event_type", models.CharField(max_length=80)),
                ("object_type", models.CharField(max_length=80)),
                ("object_id", models.CharField(blank=True, max_length=100)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("tombstone", models.BooleanField(default=False)),
                ("actor_kind", models.CharField(default="user", max_length=24)),
                ("token_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="project_changes", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="changes", to="projects.project")),
            ],
            options={"ordering": ("project", "sequence")},
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("actor_kind", models.CharField(default="user", max_length=24)),
                ("token_id", models.UUIDField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, max_length=100)),
                ("action", models.CharField(max_length=100)),
                ("object_type", models.CharField(blank=True, max_length=80)),
                ("object_id", models.CharField(blank=True, max_length=100)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_events", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="audit_events", to="projects.project")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("endpoint", models.CharField(max_length=200)),
                ("key", models.CharField(max_length=200)),
                ("request_hash", models.CharField(max_length=64)),
                ("response_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("response_body", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("token", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="idempotency_keys", to="accounts.agenttoken")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="idempotency_keys", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(model_name="projectmembership", constraint=models.UniqueConstraint(fields=("project", "user"), name="projects_membership_project_user_uniq")),
        migrations.AddConstraint(model_name="promptrevision", constraint=models.UniqueConstraint(fields=("project", "revision"), name="projects_promptrevision_project_revision_uniq")),
        migrations.AddConstraint(model_name="searchrun", constraint=models.UniqueConstraint(condition=~models.Q(idempotency_key=""), fields=("project", "user", "idempotency_key"), name="projects_searchrun_project_user_idem_uniq")),
        migrations.AddConstraint(model_name="lead", constraint=models.UniqueConstraint(condition=~models.Q(source_listing_id=""), fields=("project", "source", "source_listing_id"), name="projects_lead_source_identity_uniq")),
        migrations.AddConstraint(model_name="lead", constraint=models.UniqueConstraint(condition=~models.Q(identity_hash=""), fields=("project", "identity_hash"), name="projects_lead_url_identity_uniq")),
        migrations.AddConstraint(model_name="leadinterest", constraint=models.UniqueConstraint(fields=("lead", "user"), name="projects_leadinterest_lead_user_uniq")),
        migrations.AddConstraint(model_name="projectchange", constraint=models.UniqueConstraint(fields=("project", "sequence"), name="projects_change_project_sequence_uniq")),
        migrations.AddConstraint(model_name="idempotencykey", constraint=models.UniqueConstraint(fields=("token", "endpoint", "key"), name="projects_idempotency_token_endpoint_key_uniq")),
        migrations.AddIndex(model_name="projectinvitation", index=models.Index(fields=("project", "invited_email", "created_at"), name="projects_pr_project_313c30_idx")),
        migrations.AddIndex(model_name="searchrun", index=models.Index(fields=("project", "status", "created_at"), name="projects_se_project_2bb9e2_idx")),
        migrations.AddIndex(model_name="lead", index=models.Index(fields=("project", "status"), name="projects_le_project_fa515e_idx")),
        migrations.AddIndex(model_name="lead", index=models.Index(fields=("project", "date_confidence"), name="projects_le_project_edd939_idx")),
        migrations.AddIndex(model_name="projectchange", index=models.Index(fields=("project", "created_at"), name="projects_pr_project_e2b616_idx")),
        migrations.AddIndex(model_name="auditevent", index=models.Index(fields=("project", "created_at"), name="projects_au_project_2129bb_idx")),
        migrations.AddIndex(model_name="idempotencykey", index=models.Index(fields=("expires_at",), name="projects_id_expires_e083c1_idx")),
    ]
