// Add new listing objects to this array. See README.md before editing.
window.SUBLET_LISTINGS = [
  {
    id: "leasebreak-398175",
    title: "Furnished room with rooftop & backyard",
    price: "$1,120 + $185 utilities",
    location: "1869 Madison St · Ridgewood, Queens",
    dates: "Aug 31–Sep 30; 1-month minimum",
    type: "shared",
    dateFit: "strong",
    source: "LeaseBreak",
    url: "https://www.leasebreak.com/short-term-rental-details/398175/1869-madison-street",
    summary: "Furnished room in a renovated 5-bedroom/2-bath duplex near the L and M. Rooftop, backyard, laundry and billiards; listing asks for a clean housemate with good energy.",
    unknowns: ["Ask whether Sep 1 move-in is possible and confirm guest/crash policy.", "Likely near the edge of the 45-minute commute target; verify at work hours."],
    parks: "Park on the same block",
    added: "2026-08-14"
  },
  {
    id: "leasebreak-401831",
    title: "Furnished Bed-Stuy room",
    price: "$1,160/mo",
    location: "533 Nostrand Ave · Bedford-Stuyvesant, Brooklyn",
    dates: "Aug 31 start; 1-month minimum",
    type: "shared",
    dateFit: "strong",
    source: "LeaseBreak",
    url: "https://www.leasebreak.com/short-term-rental-details/401831/533-nostrand-avenue",
    summary: "Furnished room in a 4-bedroom/1-bath share. A low-cost Brooklyn lead with a one-month minimum and an Aug 31 earliest start.",
    unknowns: ["Confirm Sep 1–30 availability, roommate fit, total fees and guest policy.", "Confirm commute to W 124th stays within 45 minutes."],
    parks: "Unknown",
    added: "2026-08-14"
  },
  {
    id: "leasebreak-399020",
    title: "Furnished Bushwick room — exact Sep start",
    price: "$1,250/mo",
    location: "148 Cornelia St · Bushwick, Brooklyn",
    dates: "Sep 1 start; 1-month minimum",
    type: "shared",
    dateFit: "strong",
    source: "LeaseBreak",
    url: "https://www.leasebreak.com/short-term-rental-details/399020/148-cornelia-street",
    summary: "Furnished room in a 4-bedroom/1-bath apartment. The live listing shows a September 1 start and permits a one-month term.",
    unknowns: ["Confirm Sep 30 move-out, roommate fit, fees and guest policy.", "Bushwick may be near the 45-minute commute limit; check the exact route."],
    parks: "Unknown",
    added: "2026-08-14"
  },
  {
    id: "leasebreak-401111",
    title: "Furnished Bushwick room — exact Sep start",
    price: "$1,260/mo",
    location: "951 Madison St · Bushwick, Brooklyn",
    dates: "Sep 1 start; 1-month minimum",
    type: "shared",
    dateFit: "strong",
    source: "LeaseBreak",
    url: "https://www.leasebreak.com/short-term-rental-details/401111/951-madison-street",
    summary: "Furnished room in a 4-bedroom/1-bath share. Very budget-friendly and explicitly available from September 1 for a one-month minimum.",
    unknowns: ["Confirm Sep 30 move-out, household vibe, fees and guests.", "Verify commute time at the actual work hours."],
    parks: "Unknown",
    added: "2026-08-14"
  },
  {
    id: "leasebreak-401950",
    title: "Park Slope furnished room",
    price: "$1,280/mo",
    location: "688 Union St · Park Slope, Brooklyn",
    dates: "Aug 31 start; 1-month minimum",
    type: "shared",
    dateFit: "strong",
    source: "LeaseBreak",
    url: "https://www.leasebreak.com/short-term-rental-details/401950/688-union-street",
    summary: "Furnished room in a 4-bedroom/1-bath apartment. Close to the preferred Fort Greene area and likely convenient to multiple subway routes.",
    unknowns: ["Confirm Sep 1–30 dates, roommate vibe, all fees and guest/crash policy."],
    parks: "Near Prospect Park (verify exact walk)",
    added: "2026-08-14"
  },
  {
    id: "leasebreak-401559",
    title: "Crown Heights furnished room",
    price: "$1,350/mo",
    location: "104 Rogers Ave · Crown Heights, Brooklyn",
    dates: "Sep 1 start; 1-month minimum",
    type: "shared",
    dateFit: "strong",
    source: "LeaseBreak",
    url: "https://www.leasebreak.com/short-term-rental-details/401559/104-rogers-avenue",
    summary: "Furnished room in a 4-bedroom/2-bath apartment. Exact September 1 start, one-month minimum, and within the preferred broader Brooklyn zone.",
    unknowns: ["Confirm Sep 30 move-out, roommate fit, fees and guest policy.", "Check commute time to W 124th."],
    parks: "Near Prospect Park (verify exact walk)",
    added: "2026-08-14"
  },
  {
    id: "leasebreak-395984",
    title: "Bushwick furnished room",
    price: "$1,350/mo",
    location: "223 Weirfield St · Bushwick, Brooklyn",
    dates: "Sep 1 start; 1-month minimum",
    type: "shared",
    dateFit: "strong",
    source: "LeaseBreak",
    url: "https://www.leasebreak.com/short-term-rental-details/395984/223-weirfield-street",
    summary: "Furnished room in a 4-bedroom/1-bath share. The live page advertises a September 1 start and one-month minimum.",
    unknowns: ["Confirm Sep 30 move-out, roommates, fees, guest policy and commute."],
    parks: "Unknown",
    added: "2026-08-14"
  },
  {
    id: "leasebreak-393122",
    title: "Flexible East Harlem room",
    price: "$1,425–$2,425/mo",
    location: "23 E 109th St · East Harlem, Manhattan",
    dates: "Immediate; 1-month minimum",
    type: "shared",
    dateFit: "verify",
    source: "LeaseBreak",
    url: "https://www.leasebreak.com/short-term-rental-details/393122/23-east-109th-street",
    summary: "Room in a 4-bedroom/2-bath apartment with flexible furnishing. Strong location for the work commute and within budget at the listed range.",
    unknowns: ["The quoted range varies by room/dates; request Sep 1–30 price and availability.", "Confirm household fit and guest policy."],
    parks: "Near Central Park / Marcus Garvey Park",
    added: "2026-08-14"
  },
  {
    id: "leasebreak-376081",
    title: "Upper West Side / Morningside room",
    price: "$1,625–$2,650/mo",
    location: "205 W 109th St · Upper West Side, Manhattan",
    dates: "Immediate; 1-month minimum",
    type: "shared",
    dateFit: "verify",
    source: "LeaseBreak",
    url: "https://www.leasebreak.com/short-term-rental-details/376081/205-west-109th-street",
    summary: "Room in a 3-bedroom/1-bath apartment, very convenient to W 124th and close to Morningside/Central Park. Some rooms in the advertised range are below budget.",
    unknowns: ["Ask which Sep 1–30 room is at or below $2,500.", "Confirm furnishing, roommates, fees and guests."],
    parks: "Close to Morningside Park and Central Park",
    added: "2026-08-14"
  },
  {
    id: "padmapper-63447757",
    title: "Furnished room by W 135th — one-month minimum",
    price: "$1,500/mo",
    location: "209 W 135th St · Harlem, Manhattan",
    dates: "Sep 1 start; 1-month minimum",
    type: "shared",
    dateFit: "strong",
    source: "PadMapper",
    url: "https://www.padmapper.com/rentals/63447757/room-for-rent-at-209-west-135th-st-new-york-ny-10030-new-york-ny-10030",
    summary: "Furnished room in a 4-bedroom apartment, extremely close to work. No broker fee; kitchen includes dishwasher, oven and microwave.",
    unknowns: ["Confirm Sep 30 move-out, household makeup, bathroom count and guest/crash policy."],
    parks: "Near St. Nicholas Park / Jackie Robinson Park",
    added: "2026-08-14"
  },
  {
    id: "craigslist-crown-heights-950",
    title: "Sunlit Crown Heights room — month to month",
    price: "$950 + ~$100–150 utilities",
    location: "Crown Heights, Brooklyn",
    dates: "Sep 1 move-in; month-to-month",
    type: "shared",
    dateFit: "strong",
    source: "Craigslist",
    url: "https://www.craigslist.org/view/d/brooklyn-cozy-sunlit-room-in/4FiHMSouKDJYYSmbnyeFZY",
    summary: "Furnished private room with two roommates in a quiet, clean household. Shared bathroom and no laundry on site, but the price leaves plenty of budget margin.",
    unknowns: ["Confirm Sep 30 move-out, exact address/transit, roommate fit and overnight guests."],
    parks: "Unknown",
    added: "2026-08-14"
  },
  {
    id: "craigslist-park-slope-furnished-1700",
    title: "Temporary furnished Park Slope bedroom",
    price: "$1,700 incl. utilities",
    location: "Park Slope, Brooklyn",
    dates: "One-month sublet; September availability unknown",
    type: "shared",
    dateFit: "verify",
    source: "Craigslist",
    url: "https://www.craigslist.org/view/d/brooklyn-furnished-bedroom-park-slope/wBvsgpqP2BbVMJfvmHA6DE",
    summary: "Furnished bedroom in a shared brownstone with quiet professional roommates, within about five minutes of major transit. The ad explicitly supports a temporary one-month stay.",
    unknowns: ["Listing originally says available Aug 6; ask whether Sep 1–30 is open.", "Confirm exact address, roommate fit and guest policy."],
    parks: "Park Slope; Prospect Park proximity likely, exact distance unknown",
    added: "2026-08-14"
  },
  {
    id: "reddit-nycapartments-1vj2b5z",
    title: "Bushwick en-suite room in 2BR/2BA",
    price: "$2,000 + utilities",
    location: "Jefferson L area · Bushwick, Brooklyn",
    dates: "Sep 1–Oct 30 advertised",
    type: "shared",
    dateFit: "verify",
    source: "Reddit",
    url: "https://www.reddit.com/r/NYCapartments/comments/1vj2b5z/bushwick_room_available_911030_private_en_suite/",
    summary: "Private furnished or unfurnished bedroom and bath in a 2BR/2BA with in-unit laundry and dishwasher. The existing roommate is described as calm.",
    unknowns: ["Ask whether the poster will accept Sep 1–30 only.", "Confirm guest policy and commute at work hours."],
    parks: "Near Maria Hernandez Park (verify distance)",
    added: "2026-08-14"
  },
  {
    id: "reddit-nycapartments-1vkfyxs",
    title: "Furnished Bushwick room with private bath",
    price: "$1,850 + utilities",
    location: "Wilson L area · Bushwick, Brooklyn",
    dates: "Aug 16–Oct 31 advertised",
    type: "shared",
    dateFit: "verify",
    source: "Reddit",
    url: "https://www.reddit.com/r/NYCapartments/comments/1vkfyxs/fully_furnished-room-with-private-bathroom/",
    summary: "Furnished private room and bathroom in a 2BR/2BA. The other roommate is described as clean and peaceful; transit is via the Wilson L.",
    unknowns: ["Ask whether September alone is acceptable.", "Confirm utilities, guests and commute time."],
    parks: "Unknown",
    added: "2026-08-14"
  },
  {
    id: "reddit-nycapartments-1vbydsz",
    title: "Brooklyn 2BR share — one month negotiable",
    price: "$1,500/mo",
    location: "Chauncey J / Bushwick-Aberdeen L · Brooklyn",
    dates: "Sep 1–Oct 29 advertised; one month may be possible",
    type: "shared",
    dateFit: "verify",
    source: "Reddit",
    url: "https://www.reddit.com/r/NYCapartments/comments/1vbydsz/brooklyn_room_in_2br_sep_1_oct_29_1500mo/",
    summary: "Room in a 2BR one block from the Chauncey J and five blocks from the Bushwick-Aberdeen L. Poster describes the roommate as chill and says a one-month arrangement may be possible.",
    unknowns: ["Confirm Sep 1–30 in writing and ask about guests.", "Room has a cot rather than a mattress; clarify furnishings."],
    parks: "Unknown",
    added: "2026-08-14"
  },
  {
    id: "reddit-nycapartments-1vh9of3",
    title: "Bushwick room with backyard — women only",
    price: "$1,450 + ~$100–150 utilities",
    location: "DeKalb L · Bushwick, Brooklyn",
    dates: "Flexible move-in through Sep 30",
    type: "shared",
    dateFit: "strong",
    source: "Reddit",
    url: "https://www.reddit.com/r/NYCapartments/comments/1vh9of3/female_roommate_wanted_bushwick_aug_15_sept_30/",
    summary: "Private room in a 3BR/1.5BA with private backyard and basement, shared with two friendly women and a dog. Move-in is flexible/prorated and the advertised end date is September 30.",
    unknowns: ["Confirm Sep 1 move-in, overnight guests and commute.", "Requires a female tenant, 650+ credit and 40× income; verify friend qualifies."],
    parks: "Near Maria Hernandez Park",
    added: "2026-08-14"
  },
  {
    id: "sabbaticalhomes-122765",
    title: "Entire furnished 1BR in leafy Ditmas Park",
    price: "$2,250/mo",
    location: "Ditmas Park, Brooklyn",
    dates: "Sep 1 2026–Jan 31 2027 advertised",
    type: "entire",
    dateFit: "verify",
    source: "SabbaticalHomes",
    url: "https://www.sabbaticalhomes.com/rental/122765",
    summary: "Entire one-bedroom at the target budget, in a residential neighborhood near B/Q transit and Prospect Park. A promising private-space option if the owner will split the advertised term.",
    unknowns: ["Ask whether Sep 1–30 alone is accepted; no minimum was visible in research.", "Confirm guest policy, fees and exact commute."],
    parks: "Near Prospect Park",
    added: "2026-08-14"
  },
  {
    id: "semestersublet-ues-bright-2br",
    title: "UES furnished bedroom at the budget ceiling",
    price: "$2,500/mo",
    location: "Upper East Side, Manhattan",
    dates: "September 2026 advertised",
    type: "shared",
    dateFit: "verify",
    source: "Semester Sublet",
    url: "https://semestersublet.com/properties/big-bright-furnished-2-bedroom-apt-on-ues/",
    summary: "Large, bright furnished private bedroom in a 2-bedroom apartment. Manhattan location should make the Harlem commute plausible and the ad references September 2026.",
    unknowns: ["Confirm exact Sep 1–30 dates, current availability, roommate, fees and guest policy."],
    parks: "Central Park proximity likely; verify exact location",
    added: "2026-08-14"
  },
  {
    id: "spareroom-greenpoint-park-search",
    title: "Large Greenpoint room overlooking McGolrick Park",
    price: "$1,800 incl. bills",
    location: "McGolrick Park · Greenpoint, Brooklyn",
    dates: "Sep 1 availability shown",
    type: "shared",
    dateFit: "verify",
    source: "SpareRoom",
    url: "https://www.spareroom.com/rooms-for-rent/brooklyn/greenpoint",
    summary: "Large double-room setup with a bedroom plus living room, private entrance and park view. This link opens the live Greenpoint results; find the title “Large Light Filled Room on Park in Greenpoint.”",
    unknowns: ["Confirm one-month term, Sep 30 move-out, roommates, exact address and guests."],
    parks: "Directly overlooking McGolrick Park",
    added: "2026-08-14"
  },
  {
    id: "spareroom-williamsburg-september-search",
    title: "Williamsburg furnished room — Sep 1 to Oct 1",
    price: "$2,000 incl. bills",
    location: "Williamsburg, Brooklyn 11211",
    dates: "Sep 1–Oct 1",
    type: "shared",
    dateFit: "strong",
    source: "SpareRoom",
    url: "https://www.spareroom.com/rooms-for-rent/nyc?posted_by=roommates",
    summary: "Private furnished room in a 4BR share with the target month explicitly shown. This link opens live roommate-posted results; find “Private Furnished Room September 1 to October 1.”",
    unknowns: ["Confirm whether Oct 1 move-out means vacating that morning, plus exact address, roommate vibe and guests."],
    parks: "Unknown",
    added: "2026-08-14"
  },
  {
    id: "spareroom-greenpoint-two-rooms-search",
    title: "Two furnished Greenpoint rooms near G train",
    price: "$1,350–$1,400/mo",
    location: "Greenpoint, Brooklyn",
    dates: "Sep 1 availability shown",
    type: "shared",
    dateFit: "verify",
    source: "SpareRoom",
    url: "https://www.spareroom.com/rooms-for-rent/brooklyn",
    summary: "Two furnished rooms in a house near the G train. The Brooklyn results page currently shows this lead, offering a useful low-cost option near the preferred Brooklyn area.",
    unknowns: ["Search-page lead: locate the current card and confirm it is still live.", "Confirm one-month term, exact dates, address, household and guests."],
    parks: "Unknown",
    added: "2026-08-14"
  },
  {
    id: "spareroom-bedstuy-ensuite-search",
    title: "Bed-Stuy furnished en-suite room",
    price: "$1,425/mo",
    location: "Quincy St · Bedford-Stuyvesant, Brooklyn",
    dates: "Sep 1 availability shown",
    type: "shared",
    dateFit: "verify",
    source: "SpareRoom",
    url: "https://www.spareroom.com/rooms-for-rent/brooklyn",
    summary: "Furnished private room with a private bathroom, shown in current Brooklyn search results. Good price and potential transit fit.",
    unknowns: ["Search-page lead: locate the current card and confirm one-month availability.", "Confirm exact address, move-out, fees, roommates and guests."],
    parks: "Unknown",
    added: "2026-08-14"
  },
  {
    id: "listingsproject-washington-heights-9cce0ad9",
    title: "Low-cost Washington Heights room near A train",
    price: "$1,200 incl. utilities",
    location: "Washington Heights, Manhattan",
    dates: "Aug 19–Apr 30 advertised; shorter stay possible",
    type: "shared",
    dateFit: "verify",
    source: "Listings Project",
    url: "https://www.listingsproject.com/listings/room-available-in-lovely-washington-heights-apartment-9cce0ad9-91fc-4a42-b633-cad94d11e2e0",
    summary: "Private 103-square-foot room in a 3BR, one block from the A and near the 1. Shared with a beagle; the location should offer an easy commute to W 124th.",
    unknowns: ["The usual minimum is three months, but the lister explicitly says shorter stays may be possible; request Sep 1–30.", "Confirm household fit and guest policy."],
    parks: "Near Fort Tryon / Highbridge parks; verify exact distance",
    added: "2026-08-14"
  },
  {
    id: "spareroom-102591796",
    title: "Furnished Kips Bay room — one-month stays allowed",
    price: "$2,400/mo",
    location: "Kips Bay, Manhattan",
    dates: "Sep 1 shown; year needs verification",
    type: "shared",
    dateFit: "verify",
    source: "SpareRoom",
    url: "https://www.spareroom.com/rooms-for-rent/manhattan/kips_bay/102591796",
    summary: "Furnished room in a 2BR near the 6 train and Madison Square Park. The ad permits one-month stays and current search text showed a September 1 opening.",
    unknowns: ["Page metadata and current search crawl disagree on 2025 vs 2026; verify immediately.", "Confirm exact Sep dates, roommate, fees and guests."],
    parks: "Near Madison Square Park",
    added: "2026-08-14"
  },
  {
    id: "spareroom-greenpoint-apartment-search",
    title: "Greenpoint rooms beside McGolrick Park",
    price: "$1,590–$1,720/mo",
    location: "McGolrick Park · Greenpoint, Brooklyn",
    dates: "Sep 1 availability shown",
    type: "shared",
    dateFit: "verify",
    source: "SpareRoom",
    url: "https://www.spareroom.com/rooms-for-rent/brooklyn/greenpoint",
    summary: "Two available rooms in a Greenpoint apartment near McGolrick Park, shown in the current neighborhood results under “Greenpoint Apartment near McGolrick Park.”",
    unknowns: ["Confirm a one-month term; the result may normally seek a longer lease.", "Confirm direct listing URL, exact address, household, fees and guests."],
    parks: "Beside McGolrick Park",
    added: "2026-08-14"
  }
];
